# syntax=docker/dockerfile:1

FROM golang:1.20-alpine AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download
RUN go mod verify

COPY .env ./
COPY *.go ./
COPY api/ ./api/

RUN go build -o ./breadstick .

EXPOSE 3000

CMD ["./breadstick"]
