# syntax=docker/dockerfile:1

FROM golang:1.20-alpine AS build

ARG PORT=3000
ENV PORT=$PORT

ARG TOKEN
ENV API_TOKEN=$TOKEN

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download
RUN go mod verify

COPY .env ./
COPY *.go ./
COPY api/ ./api/

RUN go build -o ./breadstick .

ARG PORT=3000
EXPOSE $PORT

CMD ["./breadstick"]
